name: Maven Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          # Temurin is the stable Eclipse Adoptium build of OpenJDK
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Maven
        run: mvn -B clean install
